version: '3'
services:
  ftp:
    image: vimagick/vsftpd
    ports:
      - 20-21:20-21
      - 30000-30010:30000-30010
    restart: always
    volumes:
      - ./pam.d/vsftpd:/etc/pam.d/vsftpd
      - ./vsftpd:/etc/vsftpd
      - /root/admin:/home/virtual/admin
